LOST_TREASURE_DATA_INDEX_X = 1
LOST_TREASURE_DATA_INDEX_Y = 2
LOST_TREASURE_DATA_INDEX_TEXTURE = 3
LOST_TREASURE_DATA_INDEX_ITEMID = 4

LOST_TREASURE_MARK_OPTIONS_USING = 1
LOST_TREASURE_MARK_OPTIONS_INVENTORY = 2
LOST_TREASURE_MARK_OPTIONS_ALL = 3

LOST_TREASURE_PIN_KEY_MAP = 1
LOST_TREASURE_PIN_KEY_COMPASS = 2

LOST_TREASURE_PIN_TYPE_TREASURE = 1
LOST_TREASURE_PIN_TYPE_SURVEYS = 2

LOST_TREASURE_PIN_TYPE_DATA =
{
	[LOST_TREASURE_PIN_TYPE_TREASURE] =
	{
		pinName = "LostTreasure_TreasureMapPin",
		specializedItemType = SPECIALIZED_ITEMTYPE_TROPHY_TREASURE_MAP,
		compareString = zo_strlower(GetString(SI_LOST_TREASURE_COMPARE_TREASURE)),
		name = GetString(SI_LOST_TREASURE_TREASURE_MAPS),
		interactionType = INTERACTION_NONE,
	},
	[LOST_TREASURE_PIN_TYPE_SURVEYS] =
	{
		pinName = "LostTreasure_SurveyReportPin",
		specializedItemType = SPECIALIZED_ITEMTYPE_TROPHY_SURVEY_REPORT,
		compareString = zo_strlower(GetString(SI_LOST_TREASURE_COMPARE_SURVEY)),
		name = GetString(SI_LOST_TREASURE_SURVEY_REPORTS),
		interactionType = INTERACTION_HARVEST,
	},
}